### ISSUE TITLE
.rust.o.cmd: No such file or directory

### ISSUE THREAD

**Issue by Skallwar** [jbaublitz/knock-out#9] opened 2021-02-28 15:50 UTC
Hello,

While trying to build, I get this error:
``.rust.o.cmd: No such file or directory``

Linux version: ``uname -r =  5.10.19-1-lts``

**Comment by jbaublitz** [comment] 2021-03-01 00:49
Can you please show me how you're invoking the build?

**Comment by Skallwar** [comment] 2021-03-01 17:28
> Can you please show me how you're invoking the build?

I just ran ``make`` after setting up nightly as my default toolchain

**Comment by jbaublitz** [comment] 2021-03-07 16:20
I can't reproduce this on my system. I've been digging into out of tree kernel module builds so I'll update you with more information as I come up with it.

**Comment by joroec** [comment] 2021-04-21 08:48
There was a kernel commit (around version 5.8), not sure exactly, that changed a missing `.o.cmd` file from a warning to an error.
I can reproduce the error on an Ubuntu 20.04 system (kernel `5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`) with Rust toolchain `rustc 1.53.0-nightly (6df26f897 2021-04-20)`.
A quick fix is to generate the empty file manually. This tells Kbuild that there are no build dependencies for this file:
```shell
touch src/.rust.o.cmd
```
and repeat the build with `make`. The build should now succeed.

[Here](https://stackoverflow.com/questions/63413757/problems-building-driver-on-linux-kernel-5-8-x) are some more information.

Note, however, that the toolchain `rustc 1.53.0-nightly (6df26f897 2021-04-20)` still generates wrong relocation symbols. See this [issue](https://github.com/jbaublitz/knock-out/issues/11) for more information.

**Comment by jbaublitz** [comment] 2021-10-02 18:32
Fixed by 449c36db078836b4c2205937cbb2c6c82b850689.

**Closed as completed by jbaublitz** 2021-10-02 18:32 UTC
